version: "3.9"

services:
  web:
    build: .
    container_name: nossotrello_web
    restart: always
    command: gunicorn nossotrello.wsgi:application -b 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - ./data/sqlite:/app/db
      - ./static:/app/staticfiles
      - ./media:/app/media
    environment:
      DJANGO_SETTINGS_MODULE: nossotrello.settings
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nossotrello_nginx
    restart: always
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx/nossotrello.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: nossotrello_certbot
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nossotrello.conf:/etc/nginx/conf.d/default.conf
    entrypoint: /bin/sh
