services:
  web:
    build: .
    restart: always
    command: sh -lc "mkdir -p /app/staticfiles && python manage.py collectstatic --noinput && gunicorn nossotrello.wsgi:application -b 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - ./data/sqlite:/app/db
      - ./static:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: nossotrello.settings
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-8081}:80"
      - "${NGINX_HTTPS_PORT:-8443}:443"
    volumes:
      - ./nginx/nossotrello.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nossotrello.conf:/etc/nginx/conf.d/default.conf
    entrypoint: /bin/sh
